services:
  binoculars:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn app:app --host 0.0.0.0 --port 7860
    ports:
      - "7860:7860"  # Gradio app port
      - "8080:8080"  # fastapi app port
    volumes:
      - .:/app 
    networks:
      - net
    environment:
      - ENVIRONMENT=development
      - BINOCULARS_FORCE_TO_CPU=false
      - AUTHORIZED_API_KEYS=my_api_key_1|my_api_key_2
      - SECRET_KEY=my_secret_key
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - PORT=7860

networks:
  net: