services:
  binoculars:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: python3.10 app.py
    ports:
      - "7860:7860"  # Gradio app port
      - "8080:8080"  # fastapi app port
    volumes:
      - .:/app 
    networks:
      - net
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - ENVIRONMENT=development
      - BINOCULARS_FORCE_TO_CPU=false
      - AUTHORIZED_API_KEYS=my_api_key_1|my_api_key_2
      - SECRET_KEY=my_secret_key
      - FASTAPI_NO_LONG_RUNNING_TASK=false
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

networks:
  net: