services:
  binoculars:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn app:app --host 0.0.0.0 --port 7860 --reload
    ports:
      - "7860:7860"  # Gradio app port
      - "8080:8080"  # fastapi app port
    volumes:
      - .:/app 
    networks:
      - net
    environment:
      - ENVIRONMENT=development
      - BINOCULARS_FORCE_TO_CPU=false
      - API_AUTHORIZED_KEYS=my_api_key_1|my_api_key_2
      - API_SECRET_KEY=my_secret_key
      - API_ACCESS_TOKEN_EXPIRE_MINUTES=60
      - PORT=7860
      - BINOCULARS_THRESHOLD=0.99963529763794
      - BINOCULARS_OBSERVER_MODEL_NAME=HuggingFaceTB/SmolLM2-135M
      - BINOCULARS_PERFORMER_MODEL_NAME=HuggingFaceTB/SmolLM2-135M-Instruct
      - HF_HOME=/home/user/.cache/huggingface/hub
      - HF_TOKEN=
      - MODEL_CHUNK_SIZE=10000000
      - MODEL_BATCH_SIZE=1
      - MODEL_MINIMUM_TOKENS=64
      - MAX_FILE_SIZE_BYTES=10000000
      - FLATTEN_BATCH=false

networks:
  net: